[0;31mTypeError: test/errors/function/too_many_args.np:5:3
[0m[0mcallable `fn` accepts 0 arguments but 1 were given[0m
[0m  5| fn(1)
[0m
exitcode=1